# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qround',
            name='round_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='qteam',
            name='team_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
