# Generated by Django 5.2.7 on 2025-10-26 18:02

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwis', '0002_auto_20160701_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=200, unique=True)),
                ('max_score', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.RemoveField(
            model_name='qanswer',
            name='rnd',
        ),
        migrations.RemoveField(
            model_name='qanswer',
            name='team',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=6)),
                ('rnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwis.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwis.team')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.DeleteModel(
            name='QRound',
        ),
        migrations.DeleteModel(
            name='QAnswer',
        ),
        migrations.DeleteModel(
            name='QTeam',
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('team', 'rnd'), name='unique_team_round_answer', violation_error_message='A team can only have one answer per round.'),
        ),
    ]
