# Generated by Django 5.2.7 on 2025-10-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwis', '0003_round_team_remove_qanswer_rnd_remove_qanswer_team_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='unique_team_round_answer',
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('team', 'rnd'), name='unique_team_round_answer', violation_error_message='A team can only have one answer per round.'),
        ),
    ]
