# Generated by Django 5.2.8 on 2025-11-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwis', '0004_remove_answer_unique_team_round_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hidden_count', models.IntegerField(default=0)),
            ],
        ),
    ]
