# Generated by Django 5.2.8 on 2025-11-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwis', '0005_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='hidden_count',
            new_name='reveal_count',
        ),
    ]
