# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='QRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=200)),
                ('max_score', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='QTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='qanswer',
            name='rnd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwis.QRound'),
        ),
        migrations.AddField(
            model_name='qanswer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwis.QTeam'),
        ),
    ]
