# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-21 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwis', '0002_auto_20160701_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qanswer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='qround',
            options={'verbose_name': 'Round', 'verbose_name_plural': 'Rounds'},
        ),
        migrations.AlterModelOptions(
            name='qteam',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
